version: '3'
services:
  postgresql:
    container_name: votacao-postgresql
    image: postgres
    hostname: votacao-postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      TZ: America/Sao_Paulo
      PGTZ: America/Sao_Paulo
      POSTGRES_USER: votacao
      POSTGRES_PASSWORD: 42dAz4s3X8yB
      POSTGRES_DB: votacao_db
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - kafka-network

  votacao:
    container_name: votacao
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      TZ: America/Sao_Paulo
    depends_on:
      - postgresql
      - kafka
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - kafka-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.0
    restart: on-failure
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:7.0.0
    restart: on-failure
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CREATE_TOPICS=pauta-encerrada:1:3
    depends_on:
      - zookeeper
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge
