spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/votacao_db
    username: votacao
    password: 42dAz4s3X8yB
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
